In [7]:
import numpy as np
np.random.seed(0)
# Example data
n = 5  # Number of rows
m = 4  # Number of columns
cal_smx = np.random.rand(n, m)  # Random data for cal_smx
labels_smx = np.random.rand(n)  # Random data for labels_smx

# Calculate the sum of elements greater than labels_smx for each row
row_sums = np.sum(cal_smx > labels_smx[:, np.newaxis], axis=1)

print("Sum of elements greater than labels:")
print(row_sums)


Sum of elements greater than labels:
[0 1 3 1 3]


In [6]:
cal_smx[cal_smx > labels_smx[:, np.newaxis]]

array([0.891773  , 0.96366276, 0.79172504, 0.52889492, 0.92559664,
       0.83261985, 0.77815675, 0.87001215])

In [9]:
cal_smx > labels_smx[:, np.newaxis]

array([[False, False, False, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [2]:
import numpy as np

# Generate random numbers
numbers = np.random.randint(1, 1000, size=10)  # Generate integers between 1 and 1000

# Normalize the numbers to make the sum 1
normalized_numbers = numbers / np.sum(numbers)

# Round the normalized numbers to 3 decimal places
rounded_numbers = np.round(normalized_numbers, 3)

# Adjust the last number to ensure the sum is exactly 1
rounded_numbers[-1] += 1 - np.sum(rounded_numbers)

print(rounded_numbers)
print("Sum:", np.sum(rounded_numbers))

[0.02  0.132 0.241 0.235 0.083 0.018 0.035 0.069 0.081 0.086]
Sum: 1.0
